/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ipaloma_posjniproject_jni_NativeUtilitiesClass */

#ifndef _Included_com_ipaloma_posjniproject_jni_NativeUtilitiesClass
#define _Included_com_ipaloma_posjniproject_jni_NativeUtilitiesClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ipaloma_posjniproject_jni_NativeUtilitiesClass
 * Method:    saveAppInfoConfig
 * Signature: (IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ipaloma_posjniproject_jni_NativeUtilitiesClass_saveAppInfoConfig
  (JNIEnv *, jobject, jint, jint, jstring, jstring, jstring);

/*
 * Class:     com_ipaloma_posjniproject_jni_NativeUtilitiesClass
 * Method:    initUDPSocket
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ipaloma_posjniproject_jni_NativeUtilitiesClass_initUDPSocket
  (JNIEnv *, jobject);

/*
 * Class:     com_ipaloma_posjniproject_jni_NativeUtilitiesClass
 * Method:    sendWDRegisterPackage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ipaloma_posjniproject_jni_NativeUtilitiesClass_sendWDRegisterPackage
  (JNIEnv *, jobject);

/*
 * Class:     com_ipaloma_posjniproject_jni_NativeUtilitiesClass
 * Method:    sendWDFeedPackage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ipaloma_posjniproject_jni_NativeUtilitiesClass_sendWDFeedPackage
  (JNIEnv *, jobject);

/*
 * Class:     com_ipaloma_posjniproject_jni_NativeUtilitiesClass
 * Method:    sendWDUnregisterPackage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ipaloma_posjniproject_jni_NativeUtilitiesClass_sendWDUnregisterPackage
  (JNIEnv *, jobject);

/*
 * Class:     com_ipaloma_posjniproject_jni_NativeUtilitiesClass
 * Method:    closeUPDClient
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ipaloma_posjniproject_jni_NativeUtilitiesClass_closeUPDClient
  (JNIEnv *, jobject);

/*
 * Class:     com_ipaloma_posjniproject_jni_NativeUtilitiesClass
 * Method:    execCmdLine
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ipaloma_posjniproject_jni_NativeUtilitiesClass_execCmdLine
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
